## Multi Label Classification
it will only give those output for which it is trained that is if dataset consist of black jeans, red dress and red shirt, it will always give output as red dress and red shirt and never red jeans

## better to use multi output models

### Multi label classification model was trained with eager execution disabled to give 96% accuracy if the eager execution was not disabled then accuracy was coming to 60%


### Multi Output model was trained with eager execution enabled

In [1]:
from tensorflow.keras.preprocessing.image import img_to_array
from tensorflow.keras.models import load_model
import numpy as np
import argparse
import imutils
import pickle
import cv2
import os

In [2]:
image = cv2.imread("keras-multi-label\examples\example_01.jpg")
output = imutils.resize(image, width=400)

In [3]:
image = cv2.resize(image, (96, 96))
image = image.astype("float") / 255.0
image = img_to_array(image)
image = np.expand_dims(image, axis=0)

In [5]:
model = load_model("keras-multi-label\\fashion_ashish.model")
mlb = pickle.loads(open("keras-multi-label\mlb_ashish.pickle", "rb").read())

In [6]:
proba = model.predict(image)[0]

In [7]:
proba, proba.shape

(array([5.9386210e-05, 3.3431461e-06, 9.9999380e-01, 2.8268532e-05,
        1.0000000e+00, 2.0025991e-05], dtype=float32),
 (6,))

In [9]:
#ascending          descending               top 2
np.argsort(proba), np.argsort(proba)[::-1],  np.argsort(proba)[::-1][:2]

(array([1, 5, 3, 0, 2, 4], dtype=int64),
 array([4, 2, 0, 3, 5, 1], dtype=int64),
 array([4, 2], dtype=int64))